language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
before_script:
- git config --global user.name "Huan Jiang"
- git config --global user.email "bill.jiangh@gmail.com"
- sed -i'' "s~git@github.com:billjh/blog.git~https://${GH_TOKEN}:x-oauth-basic@github.com/billjh/blog.git~" _config.yml
install:
- npm install
- hexo generate
script:
- hexo deploy > deploy.log 2>&1
- cat deploy.log | sed "s~${GH_TOKEN}~TOKEN~g"
env:
  global:
    secure: i4iRfcrANIPk5q3ZqjISeW6F9vfT5wZHrWED0m2xtvfJ03ZH5K7hNPwo3z8cCIaSJkvXF1jnYIewPfV3J3guYeM4vCb5y5eKE62GMWsHjFyJdcc3XSTXMg70Z8piMz88RVOrrXnZ8sVJ8c751mPtADUXMRlzMJRs1F1AHyoi7knbKxWCTZh/hPNdaz6d1yQjPYWmcguPWKCwXyY7DkqljqCG/aYDpja4L4j9b9JiCEA6Twd9ia3Inys7+NfTRAKlfuSNOwCsBWPG+dNOBRKS7j3b757K+8fjGlvN8T1IluECMTQMkxtrrJwno0RjQUJtKb/qTCrGgcuRNzGhxRffSTKWaay7mL2zsnhCkGg4mJR3JWJPhCq+oZh4ntOnGJYZVzBT5prw5CuKTzTdDCGDwz6RiQhgMjuA4DDZqjKM0V85v3pcTO8T3H4OBNKozZ0g+DPCAy2tOHSAUQBv4zUxpuuEsrRRtowGJ4Crrq2qVrVTYmg7F5J9RR9Bb57WSXDWGUmeMxPvJCIwq/pmyBG/rYA7X8P+/TBchJtg0UonHV2R2ssODtQn8errRpenSBMH/48zXnnDLTzHjnsELB/uwffXUXGxF4s2rxcfdFgm1W0o5qmuuhT+PVHNLRjWqjwwDTtr+TIw4GQEDSObU03BQyJF0Ebrr4oNhXbmf5w2B34=
